openapi: 3.1.0

info:
    title: Dream Machine API
    summary: A RESTful API for interacting with the Dream Machine
    description: Generate images and videos using text_to_video, image_to_video, and video_to_video capabilities.
    termsOfService: https://lumalabs.ai/legal/tos
    contact:
        name: Luma AI, Inc.
        email: support@lumalabs.ai
        url: https://lumalabs.ai
    license:
        name: Proprietary
        identifier: Luma-AI-Dream-Machine-API
        url: https://lumalabs.ai/legal/tos
    version: v1alpha

servers:
    - url: http://api.lumalabs.ai/dream-machine/v1alpha
      description: Production Base URL
    - url: http://internal-api.sandbox.labs.lumalabs.ai/dream-machine/v1alpha
      description: Staging Base URL

security:
    - bearerAuth: []

resources:
    generations:
        Generation:
            type: object
            description: The generation reference object
            properties:
                id:
                    type: string
                    format: uuid
                    description: The ID of the generation
            example:
                id: '123e4567-e89b-12d3-a456-426614174000'

        Image:
            type: object
            description: The image object
            properties:
                url:
                    type: string
                    format: uri
                    description: The URL of the image
            example:
                url: 'https://example.com/image.jpg'

        Video:
            type: object
            description: The video object
            properties:
                url:
                    type: string
                    format: uri
                    description: The URL of the video
            example:
                url: 'https://example.com/video.mp4'

components:
    securitySchemes:
        bearerAuth:
            type: apiKey
            description: API Key to access the API. The API key should be prefixed with "Bearer " in the Authorization header.
            in: header
            name: Authorization

    schemas:
        Error:
            type: object
            description: The error object
            properties:
                detail:
                    type: string
                    description: The error message
            example:
                detail: 'Invalid API key provided'

        Order:
            type: string
            description: The order of the generations
            enum:
                - ascending
                - descending
            example: descending

        OrderBy:
            type: string
            description: The order by of the generations
            enum:
                - created_at
            example: created_at

        State:
            type: string
            description: The state of the generation
            enum:
                - pending
                - processing
                - completed
                - failed
            example: completed

        Assets:
            type: object
            description: The assets of the generation
            properties:
                thumbnail:
                    type: string
                    format: uri
                    description: The URL of the thumbnail
                video:
                    type: string
                    format: uri
                    description: The URL of the video
            example:
                thumbnail: 'https://example.com/thumbnail.jpg'
                video: 'https://example.com/video.mp4'

        Keyframe:
            oneOf:
                - $ref: '#/resources/generations/Generation'
                - $ref: '#/resources/generations/Image'
                - $ref: '#/resources/generations/Video'
            description: A keyframe can be either a Generation reference, an Image, or a Video
            examples:
                - generation:
                      value:
                          id: '123e4567-e89b-12d3-a456-426614174000'
                - image:
                      value:
                          url: 'https://example.com/image.jpg'
                - video:
                      value:
                          url: 'https://example.com/video.mp4'

        Keyframes:
            type: object
            description: The keyframes of the generation
            properties:
                frame0:
                    $ref: '#/components/schemas/Keyframe'
                    description: The frame 0 of the generation
                frame1:
                    $ref: '#/components/schemas/Keyframe'
                    description: The frame 1 of the generation
            example:
                frame0:
                    url: 'https://api.lumalabs.ai/dream-machine/v1alpha/images/123.jpg'
                frame1:
                    id: '123e4567-e89b-12d3-a456-426614174000'

        GenerationRequest:
            type: object
            description: The generation request object
            properties:
                prompt:
                    type: string
                    description: The prompt of the generation
                enhance_prompt:
                    type: boolean
                    description: Whether to enhance the prompt
                aspect_ratio:
                    type: string
                    pattern: ^\d+:\d+$
                    default: '16:9'
                negative_prompt:
                    type: string
                    description: The negative prompt of the generation
                loop:
                    type: boolean
                    description: Whether to loop the video
                keyframes:
                    $ref: '#/components/schemas/Keyframes'
                    description: The keyframes of the generation
            examples:
                - text_to_video:
                      value:
                          prompt: 'A serene lake surrounded by mountains at sunset'
                          enhance_prompt: true
                          aspect_ratio: '16:9'
                          negative_prompt: 'cloudy, stormy'
                          loop: true
                - image_to_video:
                      value:
                          prompt: 'A serene lake surrounded by mountains at sunset'
                          enhance_prompt: true
                          aspect_ratio: '16:9'
                          negative_prompt: 'cloudy, stormy'
                          loop: false
                          keyframes:
                              frame0:
                                  url: 'https://example.com/image.jpg'
                - image_to_video_end_frame:
                      value:
                          prompt: 'A serene lake surrounded by mountains at sunset'
                          enhance_prompt: true
                          aspect_ratio: '16:9'
                          negative_prompt: 'cloudy, stormy'
                          loop: false
                          keyframes:
                              frame1:
                                  url: 'https://example.com/image.jpg'
                - image_to_video_keyframes:
                      value:
                          prompt: 'A serene lake surrounded by mountains at sunset'
                          enhance_prompt: true
                          aspect_ratio: '16:9'
                          negative_prompt: 'cloudy, stormy'
                          keyframes:
                              frame0:
                                  url: 'https://example.com/image.jpg'
                              frame1:
                                  url: 'https://example.com/image.jpg'
                - extend_video:
                      value:
                          prompt: 'A serene lake surrounded by mountains at sunset'
                          enhance_prompt: true
                          aspect_ratio: '16:9'
                          negative_prompt: 'cloudy, stormy'
                          loop: true
                          keyframes:
                              frame0:
                                  id: '123e4567-e89b-12d3-a456-426614174000'
                - extend_video_reverse:
                      value:
                          prompt: 'A serene lake surrounded by mountains at sunset'
                          enhance_prompt: true
                          aspect_ratio: '16:9'
                          negative_prompt: 'cloudy, stormy'
                          keyframes:
                              frame1:
                                  id: '123e4567-e89b-12d3-a456-426614174000'
                - interpolate_image_to_video:
                      value:
                          prompt: 'A serene lake surrounded by mountains at sunset'
                          enhance_prompt: true
                          aspect_ratio: '16:9'
                          negative_prompt: 'cloudy, stormy'
                          keyframes:
                              frame0:
                                  url: 'https://example.com/image.jpg'
                              frame1:
                                  id: '123e4567-e89b-12d3-a456-426614174000'
                - interpolate_video_to_image:
                      value:
                          prompt: 'A serene lake surrounded by mountains at sunset'
                          enhance_prompt: true
                          aspect_ratio: '16:9'
                          negative_prompt: 'cloudy, stormy'
                          keyframes:
                              frame0:
                                  id: '123e4567-e89b-12d3-a456-426614174000'
                              frame1:
                                  url: 'https://example.com/video.mp4'

        GenerationResponse:
            type: object
            description: The generation response object
            properties:
                id:
                    type: string
                    format: uuid
                    description: The ID of the generation
                state:
                    $ref: '#/components/schemas/State'
                    description: The state of the generation
                state_reason:
                    type: string
                    description: The reason for the state of the generation
                created_at:
                    type: string
                    format: date-time
                    description: The date and time when the generation was created
                updated_at:
                    type: string
                    format: date-time
                    description: The date and time when the generation was last updated
                assets:
                    $ref: '#/components/schemas/Assets'
                    description: The assets of the generation
                version:
                    type: string
                    description: The model version used for the generation eg. v1.6
                request:
                    $ref: '#/components/schemas/GenerationRequest'
            example:
                id: '123e4567-e89b-12d3-a456-426614174000'
                state: 'completed'
                state_reason: null
                created_at: '2023-06-01T12:00:00Z'
                updated_at: '2023-06-01T12:05:00Z'
                assets:
                    thumbnail: 'https://example.com/thumbnail.jpg'
                    video: 'https://example.com/video.mp4'
                version: 'v1.6'
                request:
                    prompt: 'A serene lake surrounded by mountains at sunset'
                    enhance_prompt: true
                    aspect_ratio: '16:9'
                    negative_prompt: 'cloudy, stormy'
                    loop: true
                    keyframes:
                        frame0:
                            url: 'https://example.com/image.jpg'
                        frame1:
                            id: '123e4567-e89b-12d3-a456-426614174000'

        ListGenerationResponse:
            type: object
            description: The generations response object
            properties:
                has_more:
                    type: boolean
                    description: Whether there are more generations
                count:
                    type: integer
                    description: The number of generations returned
                limit:
                    type: integer
                    description: The limit of the generations requested
                offset:
                    type: integer
                    description: The offset of the generations requested
                state:
                    $ref: '#/components/schemas/State'
                    description: The state of the generations requested
                order:
                    $ref: '#/components/schemas/Order'
                    description: The order of the generations requested
                order_by:
                    $ref: '#/components/schemas/OrderBy'
                    description: The order by of the generations requested
                from_created_at:
                    type: string
                    format: date-time
                    description: The start date of the generations requested
                to_created_at:
                    type: string
                    format: date-time
                    description: The end date of the generations requested
                generations:
                    type: array
                    items:
                        $ref: '#/components/schemas/GenerationResponse'
                    description: The generations requested
            required:
                - generations
            example:
                has_more: false
                count: 1
                limit: 100
                offset: 0
                state: 'completed'
                order: 'descending'
                order_by: 'created_at'
                from_created_at: '2023-06-01T00:00:00Z'
                to_created_at: '2023-06-02T00:00:00Z'
                generations:
                    - id: '123e4567-e89b-12d3-a456-426614174000'
                      state: 'completed'
                      state_reason: null
                      created_at: '2023-06-01T12:00:00Z'
                      updated_at: '2023-06-01T12:05:00Z'
                      assets:
                          thumbnail: 'https://example.com/thumbnail.jpg'
                          video: 'https://example.com/video.mp4'
                      version: 'v1.6'
                      request:
                          prompt: 'A serene lake surrounded by mountains at sunset'
                          enhance_prompt: true
                          aspect_ratio: '16:9'
                          negative_prompt: 'cloudy, stormy'
                          loop: true
                          keyframes:
                              frame0:
                                  url: 'https://example.com/image.jpg'
                              frame1:
                                  id: '123e4567-e89b-12d3-a456-426614174000'

paths:
    /ping:
        get:
            summary: Ping
            description: Check if the API is running
            operationId: ping
            tags:
                - Ping
            responses:
                '200':
                    description: API is running
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        description: The message
                    example:
                        message: 'pong'
                default:
                    description: Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                    example:
                        detail: 'Invalid API key provided'

    /generations:
        post:
            summary: Create a generation
            description: Initiate a new generation with the provided prompt
            operationId: createGeneration
            tags:
                - Generations
            requestBody:
                required: true
                description: The generation request object
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/GenerationRequest'
                example:
                    prompt: 'A serene lake surrounded by mountains at sunset'
                    enhance_prompt: true
                    aspect_ratio: '16:9'
                    negative_prompt: 'cloudy, stormy'
                    loop: true
                    keyframes:
                        frame0:
                            url: 'https://example.com/image.jpg'
                        frame1:
                            id: '123e4567-e89b-12d3-a456-426614174000'
            responses:
                '201':
                    description: Generation created
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GenerationResponse'
                default:
                    description: Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'

        get:
            summary: List generations
            description: Retrieve a list of generations with optional filtering and sorting
            operationId: listGenerations
            tags:
                - Generations
            parameters:
                - name: limit
                  in: query
                  required: false
                  schema:
                      type: integer
                      default: 100
                - name: offset
                  in: query
                  required: false
                  schema:
                      type: integer
                      default: 0
                - name: state
                  in: query
                  required: false
                  schema:
                      $ref: '#/components/schemas/State'
                      description: The state of the generations requested
                - name: order
                  in: query
                  required: false
                  schema:
                      $ref: '#/components/schemas/Order'
                      description: The order of the generations requested
                - name: order_by
                  in: query
                  required: false
                  schema:
                      $ref: '#/components/schemas/OrderBy'
                      description: The order by of the generations requested
                - name: from_created_at
                  in: query
                  required: false
                  schema:
                      type: string
                      format: date-time
                - name: to_created_at
                  in: query
                  required: false
                  schema:
                      type: string
                      format: date-time
            responses:
                '200':
                    description: Generations found
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ListGenerationResponse'
                default:
                    description: Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'

    /generations/{id}:
        get:
            summary: Get a generation
            description: Retrieve details of a specific generation by its ID
            operationId: getGeneration
            tags:
                - Generations
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: string
                  description: The ID of the generation
            responses:
                '200':
                    description: Generation found
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GenerationResponse'
                default:
                    description: Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'

        delete:
            summary: Delete a generation
            description: Remove a specific generation by its ID
            operationId: deleteGeneration
            tags:
                - Generations
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: string
                  description: The ID of the generation
            responses:
                '204':
                    description: Generation deleted
                default:
                    description: Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
